plugins:
  - rubocop-minitest
  - rubocop-rake

AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  NewCops: enable
  TargetRubyVersion: 3.2

Style/ClassAndModuleChildren:
  Enabled: true
  EnforcedStyle: nested
  SafeAutoCorrect: true

Style/FrozenStringLiteralComment:
  Enabled: true
  SafeAutoCorrect: true

Metrics/MethodLength:
  Enabled: true
  Max: 20

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Minitest/MultipleAssertions:
  Enabled: false
