plugins:
  - rubocop-minitest
  - rubocop-rake

AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  NewCops: enable
  TargetRubyVersion: 3.2

Style/ClassAndModuleChildren:
  Enabled: true
  EnforcedStyle: nested
  SafeAutoCorrect: true

Style/FrozenStringLiteralComment:
  Enabled: true
  SafeAutoCorrect: true

Metrics/MethodLength:
  Enabled: true
  Max: 30
  Exclude:
    - "test/**/*"

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Minitest/MultipleAssertions:
  Enabled: false

Metrics/ClassLength:
  Enabled: true
  Exclude:
    - "test/**/*"

Metrics/AbcSize:
  Enabled: true
  Max: 30
  Exclude:
    - "test/**/*"

Metrics/CyclomaticComplexity:
  Enabled: true
  Max: 10

Layout/HeredocIndentation:
  Enabled: true
  Exclude:
    - "test/**/*"

Layout/TrailingWhitespace:
  Enabled: true
  Exclude:
    - "test/**/*"

Lint/UnusedMethodArgument:
  Enabled: true
  Exclude:
    - "lib/haml_lsp/autocorrect/*"
