#!/usr/bin/env ruby
# frozen_string_literal: true

require_relative "../lib/haml_lsp"

use_bundle = ARGV.include?("--use-bundle")
enable_lint = ARGV.include?("--enable-lint")

root_uri = ARGV.find { |arg| arg.start_with?("--root-uri=") }&.sub("--root-uri=", "")
root_uri ||= ENV["PWD"] ? "file://#{ENV["PWD"]}" : nil

HamlLsp::Server::Base.new(
  use_bundle: use_bundle,
  enable_lint: enable_lint,
  root_uri: root_uri
).start
